#if !canImport(ObjectiveC)
import XCTest

extension CSSKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CSSKitTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CSSKitTests.__allTests__CSSKitTests),
    ]
}
#endif
